### ISSUE TITLE
 if len(image.split()) == 4:

### ISSUE THREAD

**Issue by AVINASH18794** [madmaze/pytesseract#84] opened 2018-01-08 10:27 UTC
Pytesseract.image_to_string() function is giving the error.

**Comment by jsreid13** [comment] 2018-01-08 15:11
Can you provide more information on what version of pytesseract you're using, that image you were testing it on and what the full error output in the console was?

I recently merged a PR that changed that if statement to use image.getbands() instead of image.split() so I'm concerned it might have something to do with that.

**Comment by AVINASH18794** [comment] 2018-01-08 16:00
![image](https://user-images.githubusercontent.com/35220554/34679034-c1d89fbe-f4ba-11e7-8db5-901d7cc055bd.png)
![image](https://user-images.githubusercontent.com/35220554/34679120-f93a3904-f4ba-11e7-8c9b-efb430daf591.png)
![digit](https://user-images.githubusercontent.com/35220554/34679169-1cf19cc0-f4bb-11e7-95c9-b5477bc607fc.png)

 I am using pytesseract version  3.05.01. I am testing my code at digit.png

**Comment by jsreid13** [comment] 2018-01-08 16:44
Okay so this isn't a problem is the change made to that if statement, the issue is that you need to make the image a PIL Image object before running it through pytesseract. If you run pytesseract from the command line it does this for you but if you directly call the pytesseract.image_to_string method in a python script then you need to make it a PIL Image object yourself. Here is an example code on how to do this:

```
import pytesseract
import PIL.Image as Image

print(pytesseract.image_to_string(Image.open('/**path_to_picture**/digits.png')))
```
This successfully prints the characters in the image

**Comment by AVINASH18794** [comment] 2018-01-08 17:00
Can't I directly pass the image preprocessed using opencv .I have seen
examples of it .

**Comment by jsreid13** [comment] 2018-01-08 17:13
You can pass images processed using opencv into pytesseract, but you still need to wrap the image in a PIL Image object in order to provide the methods needed to run pytesseract. In this case use Image.fromarray(image) instead:

```
import pytesseract
import PIL.Image as Image
import cv2

img = cv2.imread('/**path_to_image**/digits.png')
print(pytesseract.image_to_string(Image.fromarray(img)))
```

**Comment by AVINASH18794** [comment] 2018-01-08 17:17
Thanks for clearing my doubts .

**Comment by int3l** [comment] 2018-01-08 17:25
@AVINASH18794 Thanks for reporting the issue.
As @jsreid13 mentioned, at the moment, pytesseract can't detect opencv images objects (only PIL).

So please use the solution that @jsreid13 suggests in the last post.
When we have time, we should try to add support for openCV.
It will be conditional - support will be available only if the openCV package is installed.
The reason behind this is: openCV is a large python package with big dependencies.

**Comment by int3l** [comment] 2018-01-08 18:57
Closing this one as we already have the feature request issue #83 .

**Closed by int3l** 2018-01-08 18:57 UTC

**Comment by int3l** [comment] 2018-01-08 19:58
Now you can try/test the new pytesseract version 0.1.8 from github (You can check the README file for installation instructions).
It has the @jsreid13 fixes and the new OpenCV/NumPy support for image objects.

Next week, I will ping Matt for the release of the new version on [PyPi](https://pypi.python.org/pypi/pytesseract) index, so it can be pip installed by default.
Until then - please download and test the new version :)
