### ISSUE TITLE
Feature request: return dictionary instead of string

### ISSUE THREAD

**Issue by Summer88** [madmaze/pytesseract#186] opened 2019-05-23 11:52 UTC
Thank you for your work, I've tried the image_to_osd function, it works fine but return a string that need to be parsed outside. I believe a dictionary would be more pratical:
```
stato = pytesseract.image_to_osd(Image.open(img))
out_dictionary = {}
def element_to_dict(ele):
    k,v = ele.split(':')
    out_dictionary[k]=v

def list_to_dict(thestring):
    thelist = thestring.format().split('\n')
    [element_to_dict(ele) for ele in thelist]
    return out_dictionary

status = list_to_dict(stato)
```
which return:
```
{'Page number': ' 0',
 'Orientation in degrees': ' 270',
 'Rotate': ' 90',
 'Orientation confidence': ' 5.77',
 'Script': ' Cyrillic',
 'Script confidence': ' 1.15'}

```
Would you please change in next release the behavior and return values as dictrionaries instead of string?

**Comment by int3l** [comment] 2019-05-23 13:10
Hi @Summer88 
this feature is already available - you can use the **output_type** argument to change the return type of the output to be `Output.DICT`. Please refer to the README for more information.

Maybe we can change the default output_type to be `Output.STRING`, but the problem is that, when we change this - any logic that relies on that to be string, will break.

**Comment by int3l** [comment] 2019-05-25 03:25
Closing as already implemented.

**Closed by int3l** 2019-05-25 03:25 UTC
