### ISSUE TITLE
The 'Empty page!!' warning doesn't show in the output

### ISSUE THREAD

**Issue by Yaoshicn** [madmaze/pytesseract#31] opened 2016-03-08 08:52 UTC
Hi!
When I use the tesseract in my terminal（OS X 10.11.3） like this:

```
tesseract test.png out
```

It will raise a warning:**Empty page!!**.
But when I use pytesseract in my code(Python 2.7.10) like this:

``` Python
try:
    import Image
except ImportError:
    from PIL import Image
import pytesseract

receipt = Image.open('test.png')
receipt.load()
print(pytesseract.image_to_string(receipt))

```

The output is consist of  2 empty lines.
So, the 'Empty page!!' warning doesn't show in the output.
Thanks.

**Comment by int3l** [comment] 2017-04-21 17:21
Please provide sample image.
Closing the issue, since I can't reproduce.
Feel free to reopen if you want.

**Closed by int3l** 2017-04-21 17:21 UTC
