### ISSUE TITLE
Temporary file not deleted

### ISSUE THREAD

**Issue by mredaelli** [madmaze/pytesseract#248] opened 2020-01-06 14:14 UTC
Using `image_to_string`, I see `pytesseract` invokes, for instance, 
```
tesseract /tmp/tess_k1c5ur29.PPM /tmp/tess_k1c5ur29 -l deu+fra+ita+eng txt 
```

but afterwards I still see the file `/tmp/tess_k1c5ur29.txt`.

I suspect that's because in [this line](https://github.com/madmaze/pytesseract/blob/master/src/pytesseract.py#L175) `f.name` should be used instead of `input_file_name`, but I might be wrong.

**Comment by int3l** [comment] 2020-01-07 11:41
Hi @mredaelli and thank you for reporting this.
Can you please let us know, what is your version of pytesseract?
I want to create test case for this specific issue, but I can't reproduce with pytesseract v0.3.1

**Comment by mredaelli** [comment] 2020-01-07 12:53
`f.name` is taken care of by the context, but that's only `/tmp/tess_k1c5ur29`, not `/tmp/tess_k1c5ur29.txt` file. 

`cleanup` deletes with a glob, but as it is now it only deletes 
```
input_file_name = f.name + extsep + extension
```
so the input image file, not the resulting output. 

I'm using pytesseract 0.3.1, tesseract 4.0.0, python 3.7.3 on debian 9.8.

**Comment by int3l** [comment] 2020-01-07 13:56
Yep, I will deploy the fix for this bug - the entire flow of execution is wrong.
In some cases the `cleanup` doesn't get call at all, which is the main problem.

**Closed** 2020-01-07 15:48 UTC

**Comment by int3l** [comment] 2020-01-07 16:19
You can test the new version 0.3.2 by installing directly from GitHub.
We will push the release later this month (I hope that this is the only refactoring mistake from the previous release).
