### ISSUE TITLE
how to resolve this error :  (2, 'Usage: pytesseract [-l lang] input_file')

### ISSUE THREAD

**Issue by ajbot2019** [madmaze/pytesseract#247] opened 2019-12-27 12:29 UTC
pytesseract.pytesseract.tesseract_cmd = r'/usr/local/bin/pytesseract'
img = Image.open("/content/drive/My Drive/006.jpg")
print(pytesseract.image_to_string(img))

stacktrace:

sr/local/lib/python3.6/dist-packages/pytesseract/pytesseract.py in image_to_string(image, lang, config, nice, output_type, timeout)
    346         Output.DICT: lambda: {'text': run_and_get_output(*args)},
    347         Output.STRING: lambda: run_and_get_output(*args),
--> 348     }[output_type]()
    349 
    350 

/usr/local/lib/python3.6/dist-packages/pytesseract/pytesseract.py in <lambda>()
    345         Output.BYTES: lambda: run_and_get_output(*(args + [True])),
    346         Output.DICT: lambda: {'text': run_and_get_output(*args)},
--> 347         Output.STRING: lambda: run_and_get_output(*args),
    348     }[output_type]()
    349 

/usr/local/lib/python3.6/dist-packages/pytesseract/pytesseract.py in run_and_get_output(image, extension, lang, config, nice, timeout, return_bytes)
    256         }
    257 
--> 258         run_tesseract(**kwargs)
    259         filename = kwargs['output_filename_base'] + extsep + extension
    260         with open(filename, 'rb') as output_file:

/usr/local/lib/python3.6/dist-packages/pytesseract/pytesseract.py in run_tesseract(input_filename, output_filename_base, extension, lang, config, nice, timeout)
    232     with timeout_manager(proc, timeout) as error_string:
    233         if proc.returncode:
--> 234             raise TesseractError(proc.returncode, get_errors(error_string))
    235 
    236 

TesseractError: (2, 'Usage: pytesseract [-l lang] input_file')

**Comment by int3l** [comment] 2019-12-27 16:10
Hi @ajbot2019 
This is configuration error on your end.
The problem is that you are trying to set **PY**tesseract instead of **tesseract** for the `tesseract_cmd` variable.

Pytesseract is just a wrapper/runner for [Tesseract-OCR](https://github.com/tesseract-ocr/tesseract).
So you need to install that as a dependency and then you can set the executable path to the tesseract bin file if it's still not in your system PATH.

Closing this issue since it's not related to pytesseract.
If you still have problems with setting up Tesseract itself,
please use StackOverflow or any other platform for developers.

**Closed by int3l** 2019-12-27 16:10 UTC

**Comment by BasilcM** [comment] 2020-07-20 12:42
Hi @ajbot2019  ,

You can choose this to solve your issue.

!sudo apt install tesseract-ocr
!pip install pytesseract

import pytesseract
try:
 from PIL import Image
except ImportError:
 import Image

pytesseract.pytesseract.tesseract_cmd = (
    r'/usr/bin/tesseract'
) 
extractedInformation = pytesseract.image_to_string(Image.open('/content/drive/My Drive/006.jpg'))
print(extractedInformation)
