### ISSUE TITLE
on version 0.3.6 parsing image with one line return string with multiple lines in contrast to 0.3.4

### ISSUE THREAD

**Issue by LevLavy** [madmaze/pytesseract#301] opened 2020-09-24 09:16 UTC
On version 0.3.4 when running
time_stamp = pytesseract.image_to_string(
                        new_img, lang="eng",
                        config="--psm 7 --oem 1 -c tessedit_char_whitelist=0123456789:°")
I get "12:30:21" on a test image (attached) when on 0.3.6 I get "12:30:21\n\f" which fails my code.
Using tesseract 4.1.1.
![test_file](https://user-images.githubusercontent.com/14163131/94125885-a01fac80-fe5f-11ea-98b9-201d8e20184b.png)

**Comment by int3l** [comment] 2020-09-24 11:35
Hi @LevLavy and thank you for reporting the issue.
This is a duplicate of #297

Basically we doesn't modify the output implicitly anymore.
Sorry about that, but this way it is possible to get the unmodified version, where before it wasn't possible, because pytesseract always stripped the output. So now you can do it manually by yourself. You can check for details in #297 
Closing this one since it's already addressed. Feel free to reopen if you need to.

**Closed by int3l** 2020-09-24 11:35 UTC
