### ISSUE TITLE
image_to_data returns different results than image_to_string

### ISSUE THREAD

**Issue by BSVogler** [madmaze/pytesseract#111] opened 2018-04-09 20:05 UTC
I use `image_to_string` for single digits but additionally I want to obtain the confidence value. Therefore I replaced it with `image_to_data` like this:
```python
ocrResult = pytesseract.image_to_data(digitBinary, config='-psm 10 -c tessedit_char_whitelist=0123456789', output_type="dict")
digitasNumber = ocrResult["text"][0]
```

With `image_to_string` the results are reasonably good.
With `image_to_data` every `text` dict entry is empty but for one case, where it returns two digits. the empty digits have `conf` -1 and the digit where `text` is filled the `conf` is 6.

I don't think that this is intended behavior.

**Comment by int3l** [comment] 2018-04-09 21:08
Did you tested with the tesseract executable itself?
If the results are the same as the python representation, than this is a tesseract specific problem and not pytesseract issue.

**Comment by int3l** [comment] 2018-04-29 22:13
As a workaround: you can change the image_to_data return format from dictionary to string and then you can parse it with a custom parser.

Closing this one since, there is no additional feedback.
Feel free to reopen if you want.

**Comment by BSVogler** [comment] 2018-07-15 13:53
it is a tesseract issue. Using _tsv_ output mode ignores `--psm 10`

**Comment by BSVogler** [comment] 2018-07-15 14:00
It is only partially a tesseract issue. pytesseract uses the tsv config file which causes this behavior because it contains the line `tessedit_pageseg_mode 1.` it is better to use `-c tessedit_create_tsv=1` when using the pytesseract method `image_to_data`.

PS: I am unable to reopen this issue.

**Comment by int3l** [comment] 2018-07-15 17:32
Yes, I understand that, but according to the [tsv config file](https://github.com/tesseract-ocr/tesseract/blob/master/tessdata/configs/tsv), **tessedit_create_tsv** is already set to 1.
So what are you suggesting - we should add different default value for **[tessedit_pageseg_mode](https://github.com/tessunleashed/tesseract-ocr-unleashed/wiki/Tesseract-Command-setPageSegMode)**?

**Comment by BSVogler** [comment] 2018-07-15 17:51
The default value is not the real problem here. The problem is that the tsv config is apparently loaded after the config is applied (see my use case in the first post) and overwriting the value. I tried to fix the code by myself but I didn't manage to make it work so far.

Internally it is currently called like this
```python
"tesseract" + config + image +" tsv"
```
but it should be
```python
"tesseract " + config + " -c tessedit_create_tsv=1 "+ image
```

**Comment by int3l** [comment] 2018-07-15 18:04
I'm not sure about that. According to the [official documentation](https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage) and the tests that I did, the config file should be at the end and the input image should be right after the **tesseract** executable filename:
```
tesseract imagename outputbase [options...] [configfile...]
or
tesseract imagename|imagelist|stdin outputbase|stdout [options...] [configfile...]
```
The only exception that I can see it for the long name arguments (--).

**Comment by int3l** [comment] 2018-07-15 18:17
And btw, the current order for the command that pytesseract executes is:
```
tesseract + input_image + output_image + config options + config file default preset for the specific function that is called
```
At least for the latest versions 0.2.2/02.3.

**Comment by BSVogler** [comment] 2018-07-15 19:12
I am sorry that I used the wrong order. The order of the parameters wasn't my point. I am suggesting to drop the usage of the tsv config file and set the relevant parameter (tessedit_create_tsv=1) by attaching it after the config string like this:

```python
"tesseract " + image + config + " -c tessedit_create_tsv=1"
```

**Comment by int3l** [comment] 2018-07-15 21:34
I guess that we can do this :) Thanks for the clarification.

**Closed** 2018-07-15 21:48 UTC

**Comment by int3l** [comment] 2018-07-15 22:09
I made it the default option, but I don't think that it is a good idea to append it at the end of the config, because for example, if someone wants to override the whole config, it will be impossible.

**Comment by int3l** [comment] 2018-07-16 12:19
I wanted to avoid hardcoding it, but anyway - maybe the use case is to always use this parameter.
The only problem with appending to the config is that the user don't have control over those config options anymore. But at least we are consistent with all other functions 👍 

I guess that we need a better way to express the tesseract configuration.

**Comment by mbdilaver** [comment] 2020-06-09 18:25
`image_to_string()` and `image_to_data()` still return different outputs for the same image. I'm using `4.1.1`

**Comment by int3l** [comment] 2020-06-09 20:55
`image_to_data` uses the `-c tessedit_create_tsv=1` config option. Maybe that changes something on the Tesseract side. You can test directly with the Tesseract cli itself and confirm that. Pytesseract doesn't alter the returned data from Tesseract.

**Comment by mbdilaver** [comment] 2020-06-09 21:22
CLI prints the same output of `image_to_string()` to a `.txt` file and `image_to_data()` to a `.tsv` file when I gave parameter `-c tessedit_create_tsv=1`. 

The problem is `image_to_string()` output is really good, but it doesn't have text coordinates. `image_to_data()` output has all of the additional data but it shows each word in a seperate field. 

Let's say I have an image with `Text: Hello World!` text on it. `image_to_string()` returns `Text: Hello World!` (or something similar to it) where `image_to_data()` returns `["Text:", "Hello", "World!"] (basically) and loses spaces between words. I guess I need to concatnate these words manually 😞  This is the difference I'm talking about. The result is same in terms of letters.
