### ISSUE TITLE
OCR Problem

### ISSUE THREAD

**Issue by Giusetech** [madmaze/pytesseract#314] opened 2020-11-29 15:23 UTC
When I try to make an OCR it creates a strange symbol in the string that don't allow me to make a comparison.
the code I'm using is the following:
`import pytesseract
from PIL import Image

im = Image.open(path)

temp = pytesseract.image_to_string(im, lang="eng")
print(temp)`

(path is a string that contains the path of the image.)

for example if I use this image as input:
![1status](https://user-images.githubusercontent.com/45655352/100545944-d9f5a080-325e-11eb-8b07-3e5f5352c9a7.png)

I will get as result:
![result](https://user-images.githubusercontent.com/45655352/100545999-26d97700-325f-11eb-9fac-25298396c796.PNG)

I already have tryed to resize the image or change the format.

**Comment by int3l** [comment] 2020-12-01 16:50
Hi, this must be a tesseract specific issue. pytesseract doesn't change the output from tesseract, so unfortunately I can't help here.
As a workaround you can try to filter for only ASCII characters or filter specific symbols in general.
But I guess that the best approach is to use your own language files, trained for your specific use case.

Closing this one as it's not a bug with pytesseract itself.

**Closed by int3l** 2020-12-01 16:50 UTC
