### ISSUE TITLE
greek langage letter

### ISSUE THREAD

**Issue by Quetzaal** [madmaze/pytesseract#547] opened 2024-05-20 07:18 UTC
hi, i've dowload and add "greek" OCR for tesseract, in tessdata (grc.traineddata) ... 
and it is available in python pytesseract 
 print(pytesseract.get_languages(config='')) 
=> ['ell', 'eng', 'equ', 'fra', 'frm', 'grc', 'lat', 'osd']

but, the OCR of a png-wiki-greek-page, do not send any greek letter... 
may i do something wrong... it's not o long time i use pytesseract, but it works fine in FR, EN, LAT... then why not greek ?

thanks for you anwser & explanation

**Comment by stefan6419846** [comment] 2024-05-20 07:39
Please try to run this page through plain Tesseract - I suspect that this is a general Tesseract issue and not related to *pytesseract*.

**Comment by Quetzaal** [comment] 2024-05-21 14:07
tesseract-OCR works as it should... but nothing to do have it by pyTesseract
 «  Κατά την πρώιμη τυπογραφία των έργων στην ελληνική γλώσσα περί το 1500, πολλά από τα συμπλέγματα αυτά
υιοθετήθηκαν από παλαιότερα χειρόγραφα. Σηµαντικά δείγματα από την Περίοδο αυτή προήλθαν από τα σχέδια
του Άλδου Μανούτιου στην Βενετία, Και του Κλωντ Γκαραμόντ στο Παρίσι ο οποίος δημιούργησε την Ιδιαπερα
εππυχηµένη γραμματοσειρά 6γεο5 ου γοίτο 1841 »

but nothing to do to have the same by pyTesseract
i used :  « txt = pytesseract.image_to_string(Image.open(adrimg), lang)   » into a function (def) which works for french and latin

then if you can do something, thanks

**Comment by stefan6419846** [comment] 2024-05-21 14:29
Your write-up is a bit confusing. In theory, when using the same parameters for both cases, the results should be identical. I am not aware that *pytesseract* would knowingly corrupt any output. For this reason, please provide some more details and possibly an example image as well as the parameters used for both cases.

**Comment by Quetzaal** [comment] 2024-05-21 16:08
your not wrong, i dod the test in the python console, outside my function, and it works as it should, then, there a weird something in my functions, that i have to debug... but it's really strange a first sight...

then, sorry for the disturb, but you help me a lot in bebuking my code, then (it comes from me)... 

see you, and thank a lot again

**Comment by codespearhead** [comment] 2024-09-26 12:02
@Quetzaal Does that mean the problem is solved? If so, can you tell us what the solution was and then [close this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/closing-an-issue)?

**Closed** 2024-09-30 11:39 UTC
