### ISSUE TITLE
getting incorrect value for image_to_data

### ISSUE THREAD

**Issue by jhachandan1994** [madmaze/pytesseract#292] opened 2020-08-14 19:22 UTC
when using data = pytesseract.image_to_data command the dictionary returns contains extra null value for  data['level'].

**Comment by int3l** [comment] 2020-08-14 19:25
Duplicate of https://github.com/madmaze/pytesseract/issues/290
I will create bug fix release 0.3.6 in the upcoming weekend.

**Closed by int3l** 2020-08-14 19:25 UTC
