### ISSUE TITLE
Failure to find tesseract even when on path [Windows]

### ISSUE THREAD

**Issue by GadgetSteve** [madmaze/pytesseract#272] opened 2020-05-25 16:58 UTC
On windows systems, even when tesseract **is** on the path, the following code fails:

> ```
> import pytesseract
> pytesseract.get_tesseract_version()
> 
> ```
> With the following output:
> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> c:\python38_64\lib\site-packages\pytesseract\pytesseract.py in get_tesseract_version()
>     336         return LooseVersion(
> --> 337             subprocess.check_output(
>     338                 [tesseract_cmd, '--version'], stderr=subprocess.STDOUT,
> 
> c:\python38_64\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
>     410
> --> 411     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>     412                **kwargs).stdout
> 
> c:\python38_64\lib\subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
>     488
> --> 489     with Popen(*popenargs, **kwargs) as process:
>     490         try:
> 
> c:\python38_64\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
>     853
> --> 854             self._execute_child(args, executable, preexec_fn, close_fds,
>     855                                 pass_fds, cwd, env,
> 
> c:\python38_64\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
>    1306             try:
> -> 1307                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>    1308                                          # no special security
> 
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> During handling of the above exception, another exception occurred:
> 
> TesseractNotFoundError                    Traceback (most recent call last)
> <ipython-input-2-f90f40c4899f> in <module>
> ----> 1 pytesseract.get_tesseract_version()
> 
> c:\python38_64\lib\site-packages\pytesseract\pytesseract.py in wrapper(*args, **kwargs)
>     122     def wrapper(*args, **kwargs):
>     123         if wrapper._result is wrapper:
> --> 124             wrapper._result = func(*args, **kwargs)
>     125         return wrapper._result
>     126
> 
> c:\python38_64\lib\site-packages\pytesseract\pytesseract.py in get_tesseract_version()
>     343         )
>     344     except OSError:
> --> 345         raise TesseractNotFoundError()
>     346
>     347
> 
> TesseractNotFoundError: tesseract is not installed or it's not in your PATH

**Comment by int3l** [comment] 2020-05-25 20:19
@GadgetSteve Hi and thank for reporting the issue.
This is really strange. Are you really sure that tesseract.exe is indeed in the system PATH?
Can you confirm that by starting PowerShell and running `Get-Command -All tesseract`?

**Comment by GadgetSteve** [comment] 2020-05-26 05:08
Hi, I had manually added, from the command prompt, with:
`path=%path%;"C:\Program Files\Tesseract-OCR"` _as I don't need Tesseract in every session_ & I checked with:
```
> Tesseract -v
tesseract v5.0.0-alpha.20200328
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.3.2 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5
 Found libcurl/7.59.0 OpenSSL/1.0.2o (WinSSL) zlib/1.2.11 WinIDN libssh2/1.7.0 nghttp2/1.31.0

```
I was running from ipython 7.14.0/python 3.8.2 (64) under Windows 10.

Checking from iPython `os.getenv('path')` Tesseract is on the path.

I found that either overriding `tesseract_cmd` or changing every call of `subprocess.check_output` to include the `shell=True` parameter would let pytesseract find and run tesseract.

Since the error message states "not on the path" and I knew that it was I didn't think to look for a readme _(and checking now the pip installed pytesseract does not have one available locally)_

**Comment by int3l** [comment] 2020-05-26 08:59
I still can't reproduce that behavior - I tested with the same python 3.8 setup.
Did you use the [set](https://ss64.com/nt/set.html) command in CMD to change the path?
This works perfectly for my current cmd session:
```console
set "PATH=%PATH%;C:\Program Files\Tesseract-OCR"
```

**Comment by int3l** [comment] 2020-05-26 09:56
I managed to reproduce your problem :)
You shouldn't use quotes around the additional path itself.
Either don't use quotes, or you quotes around the whole set argument like in the example above.

I will close this issue, since it's not pytesseract specific. If you have any other questions/issues, please feel free to reopen.

**Closed by int3l** 2020-05-26 09:56 UTC
